# Generated by Django 5.2.11 on 2026-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='categorization_source',
            field=models.CharField(blank=True, choices=[('ai', 'IA'), ('rule', 'Regla'), ('manual', 'Manual'), ('mock', 'Mock')], max_length=10, null=True),
        ),
    ]
